// 📂 prisma/seed/rolePermissionSeed.ts

import prisma from '@/lib/prisma';

export async function rolePermissionSeed() {
    try {
        console.log('🟢 Iniciando el seed de [rolePermissionSeed]');
        console.log('📂 Asignando permisos a los roles...');

        // ✅ Asegúrate de usar 12 caracteres
        const createdBy = '74214623';

        await prisma.rolePermission.createMany({
            data: [
                // ========================================================================
                //                         👑 SUPER ADMIN
                // ========================================================================
                ...[
                    'view_restaurant_config',
                    'edit_restaurant_config',
                    'view_all_theme',
                    'view_public_theme',
                    'create_theme',
                    'update_theme',
                    'delete_theme',
                    'restore_theme',
                    'view_document_type',
                    'create_document_type',
                    'update_document_type',
                    'delete_document_type',
                    'restore_document_type',
                    'view_account_status',
                    'update_account_status',
                    'view_permission_category',
                    'update_permission_category',
                    'view_permission',
                    'update_permission',
                    'view_role',
                    'create_role',
                    'update_role',
                    'delete_role',
                    'restore_role',
                    'assign_permissions_to_role',
                    'view_user',
                    'create_user',
                    'update_user',
                    'delete_user',
                    'restore_user',
                    'manage_user_status',
                    'manage_user_role',
                    'manage_user_session',
                    'view_user_profile',
                    'edit_user_profile',
                    'view_customer',
                    'create_customer',
                    'update_customer',
                    'delete_customer',
                    'restore_customer',
                    'manage_customer_status',
                    'manage_customer_session',
                    'view_customer_orders',
                    'view_customer_profile',
                    'edit_customer_profile',
                    'view_table_status',
                    'edit_table_status',
                    'view_restaurant_zone',
                    'create_restaurant_zone',
                    'edit_restaurant_zone',
                    'delete_restaurant_zone',
                    'restore_restaurant_zone',
                    'view_table',
                    'create_table',
                    'edit_table',
                    'delete_table',
                    'restore_table',
                    'assign_zone_table',
                    'change_status_table',
                    'view_combine_table',
                    'create_combine_table',
                    'release_combine_table',
                    'delete_combine_table',
                    'restore_combine_table',
                    // ✅ Cambiado: de table_session a command
                    'view_all_commands',
                    'view_command',
                    'open_command',
                    'edit_command',
                    'close_command',
                    'delete_command',
                    'restore_command',
                    'view_image',
                    'delete_image',
                    'restore_image',
                    'view_brand',
                    'create_brand',
                    'edit_brand',
                    'delete_brand',
                    'restore_brand',
                    'view_product_status',
                    'edit_product_status',
                    'view_product_type',
                    'create_product_type',
                    'edit_product_type',
                    'delete_product_type',
                    'restore_product_type',
                    'view_product_category',
                    'create_product_category',
                    'edit_product_category',
                    'delete_product_category',
                    'restore_product_category',
                    'view_product',
                    'create_product',
                    'edit_product',
                    'delete_product',
                    'restore_product',
                    'view_order_status',
                    'edit_order_status',
                    'view_order_item_status',
                    'edit_order_item_status',
                    'view_order',
                    'create_order',
                    'edit_order',
                    'close_order',
                    'cancel_order',
                    'delete_order',
                    'restore_order',
                    'view_order_item',
                    'add_order_item',
                    'edit_order_item',
                    'cancel_order_item',
                    'delete_order_item',
                    'restore_order_item',
                    'view_cashbox',
                    'open_cashbox',
                    'close_cashbox',
                    'update_cashbox',
                    'audit_cashbox',
                    'view_payment_method',
                    'create_payment_method',
                    'edit_payment_method',
                    'delete_payment_method',
                    'restore_payment_method',
                    'view_payment',
                    'create_payment',
                    'edit_payment',
                    'delete_payment',
                    'restore_payment',
                    'view_payment_transaction',
                    'view_inventory_movement_type',
                    'edit_inventory_movement_type',
                    'view_inventory',
                    'create_inventory',
                    'edit_inventory',
                    'delete_inventory',
                    'restore_inventory',
                    'view_inventory_movement',
                    'create_inventory_movement',
                    'edit_inventory_movement',
                    'delete_inventory_movement',
                    'restore_inventory_movement',
                    'view_order_sequence',
                    'edit_order_sequence',
                    'view_logs_general',
                    'view_logs_users',
                    'view_logs_customers',
                    'view_session',
                    'close_session',
                    'delete_session',
                    'restore_session',
                    'print_order',
                    'print_bill',
                    'print_receipt',
                    'generate_order_report',
                    'generate_cashbox_report',
                    'generate_inventory_report',
                    'generate_product_report',
                    'generate_customer_report',
                    'generate_payment_report',
                ].map((permissionCode) => ({
                    roleName: 'Super Admin',
                    permissionCode,
                    createdBy,
                })),

                // ========================================================================
                //                         👔 ADMIN
                // ========================================================================
                ...[
                    'view_restaurant_config',
                    'edit_restaurant_config',
                    'view_all_theme',
                    'view_public_theme',
                    'create_theme',
                    'update_theme',
                    'delete_theme',
                    'restore_theme',
                    'view_document_type',
                    'create_document_type',
                    'update_document_type',
                    'delete_document_type',
                    'restore_document_type',
                    'view_account_status',
                    'update_account_status',
                    'view_permission_category',
                    'update_permission_category',
                    'view_permission',
                    'update_permission',
                    'view_role',
                    'create_role',
                    'update_role',
                    'delete_role',
                    'restore_role',
                    'assign_permissions_to_role',
                    'view_user',
                    'create_user',
                    'update_user',
                    'delete_user',
                    'restore_user',
                    'manage_user_status',
                    'manage_user_role',
                    'manage_user_session',
                    'view_user_profile',
                    'edit_user_profile',
                    'view_customer',
                    'create_customer',
                    'update_customer',
                    'delete_customer',
                    'restore_customer',
                    'manage_customer_status',
                    'manage_customer_session',
                    'view_customer_orders',
                    'view_customer_profile',
                    'view_table_status',
                    'edit_table_status',
                    'view_restaurant_zone',
                    'create_restaurant_zone',
                    'edit_restaurant_zone',
                    'delete_restaurant_zone',
                    'restore_restaurant_zone',
                    'view_table',
                    'create_table',
                    'edit_table',
                    'delete_table',
                    'restore_table',
                    'assign_zone_table',
                    'change_status_table',
                    'view_combine_table',
                    'create_combine_table',
                    'release_combine_table',
                    'delete_combine_table',
                    'restore_combine_table',
                    // ✅ Cambiado: de table_session a command
                    'view_all_commands',
                    'view_command',
                    'open_command',
                    'edit_command',
                    'close_command',
                    'delete_command',
                    'restore_command',
                    'view_image',
                    'delete_image',
                    'restore_image',
                    'view_brand',
                    'create_brand',
                    'edit_brand',
                    'delete_brand',
                    'restore_brand',
                    'view_product_status',
                    'edit_product_status',
                    'view_product_type',
                    'create_product_type',
                    'edit_product_type',
                    'delete_product_type',
                    'restore_product_type',
                    'view_product_category',
                    'create_product_category',
                    'edit_product_category',
                    'delete_product_category',
                    'restore_product_category',
                    'view_product',
                    'create_product',
                    'edit_product',
                    'delete_product',
                    'restore_product',
                    'view_order_status',
                    'edit_order_status',
                    'view_order_item_status',
                    'edit_order_item_status',
                    'view_order',
                    'create_order',
                    'edit_order',
                    'close_order',
                    'cancel_order',
                    'delete_order',
                    'restore_order',
                    'view_order_item',
                    'add_order_item',
                    'edit_order_item',
                    'cancel_order_item',
                    'delete_order_item',
                    'restore_order_item',
                    'view_cashbox',
                    'open_cashbox',
                    'close_cashbox',
                    'update_cashbox',
                    'view_payment_method',
                    'create_payment_method',
                    'edit_payment_method',
                    'delete_payment_method',
                    'restore_payment_method',
                    'view_payment',
                    'create_payment',
                    'edit_payment',
                    'delete_payment',
                    'restore_payment',
                    'view_payment_transaction',
                    'view_inventory_movement_type',
                    'edit_inventory_movement_type',
                    'view_inventory',
                    'edit_inventory',
                    'view_inventory_movement',
                    'create_inventory_movement',
                    'edit_inventory_movement',
                    'view_order_sequence',
                    'edit_order_sequence',
                    'view_logs_general',
                    'view_logs_users',
                    'view_logs_customers',
                    'view_session',
                    'close_session',
                    'delete_session',
                    'restore_session',
                    'print_order',
                    'print_bill',
                    'print_receipt',
                    'generate_order_report',
                    'generate_cashbox_report',
                    'generate_inventory_report',
                    'generate_product_report',
                    'generate_customer_report',
                    'generate_payment_report',
                ].map((permissionCode) => ({
                    roleName: 'Admin',
                    permissionCode,
                    createdBy,
                })),

                // ========================================================================
                //                         👨‍🍳 CHEF
                // ========================================================================
                ...[
                    'view_order',
                    'view_order_item',
                    'view_order_item_status',
                    'change_order_item_status',
                    'print_order',
                    // ✅ Puede ver comandas (pedidos)
                    'view_command',
                ].map((permissionCode) => ({
                    roleName: 'Chef',
                    permissionCode,
                    createdBy,
                })),

                // ========================================================================
                //                         🍹 BARRA
                // ========================================================================
                ...[
                    'view_order',
                    'view_order_item',
                    'view_order_item_status',
                    'change_order_item_status',
                    'print_order',
                    // ✅ Puede ver comandas
                    'view_command',
                ].map((permissionCode) => ({
                    roleName: 'Barra',
                    permissionCode,
                    createdBy,
                })),

                // ========================================================================
                //                         🧑‍💼 MOZO
                // ========================================================================
                ...[
                    'view_table',
                    // ✅ Gestión de comandas
                    'view_command',
                    'open_command',
                    'edit_command',
                    'close_command',
                    'view_customer',
                    'view_product',
                    'view_order',
                    'create_order',
                    'add_order_item',
                    'edit_order_item',
                    'cancel_order_item',
                    'close_order',
                    'print_order',
                    'print_bill',
                    'generate_order_report',
                    'view_user_profile',
                    'view_customer_profile',
                ].map((permissionCode) => ({
                    roleName: 'Mozo',
                    permissionCode,
                    createdBy,
                })),

                // ========================================================================
                //                         💵 CAJERO
                // ========================================================================
                ...[
                    'view_order',
                    'view_payment',
                    'create_payment',
                    'view_cashbox',
                    'open_cashbox',
                    'close_cashbox',
                    'view_payment_method',
                    'print_receipt',
                    'print_bill',
                    'generate_cashbox_report',
                    'generate_payment_report',
                    'view_user_profile',
                    'view_customer_profile',
                    // ✅ Puede ver comandas para cobrar
                    'view_command',
                ].map((permissionCode) => ({
                    roleName: 'Cajero',
                    permissionCode,
                    createdBy,
                })),

                // ========================================================================
                //                         👔 SUPERVISOR
                // ========================================================================
                ...[
                    'view_table',
                    // ✅ Ver comandas (no todas, pero sí las necesarias)
                    'view_all_commands',
                    'view_command',
                    'view_customer',
                    'view_product',
                    'view_order',
                    'view_order_item',
                    'view_payment',
                    'view_cashbox',
                    'view_session',
                    'view_user_profile',
                    'view_customer_profile',
                    'generate_order_report',
                    'generate_cashbox_report',
                    'generate_inventory_report',
                    'generate_product_report',
                    'generate_customer_report',
                    'generate_payment_report',
                ].map((permissionCode) => ({
                    roleName: 'Supervisor',
                    permissionCode,
                    createdBy,
                })),
            ],
        });

        console.log('✅ Permisos asignados a roles exitosamente.\n');
    } catch (error) {
        console.error('❌ Error en el seed de [rolePermissionSeed]:', error);
        throw error;
    }
}
